[package]
name = "mimium-language-server"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
description = "Language server of mimium for IDE support"

[dependencies]
serde_json = "1.0.78"
tokio = { version = "1.17.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11.5"
ropey = "1.5.0"
chumsky = { version = "0.11", features = ["lexical-numbers"] }
mimium-lang = { workspace = true }
# these plugins are needed for obtaining type information of default plugins
mimium-midi = { workspace = true }
mimium-scheduler = { workspace = true }
mimium-guitools = { workspace = true }
mimium-symphonia = { workspace = true }

dashmap = "6.1.0"
log = { workspace = true }
