[package]
name = "mimium-diff-visualizer"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description = "visualizer for mimium live upstate algorithm explanation"


[[bin]]
name = "mimium-diff-visualizer"
path = "src/main.rs"

[dependencies]
mimium-lang = { workspace = true }
state-tree = { workspace = true }
anyhow = "1.0"
